[package]
name = "grade_history"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
once_cell = "1.19.0"
plotters = "0.3.5"
scraper = "0.18.1"
ureq = { version = "2.9.1", features = ["cookies"] }
