[package]
name = "pdf_splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
indicatif = { version = "0.17.6", features = ["rayon"] }
lopdf = "0.31.0"
rayon = "1.7.0"
regex = "1.9.5"
