[workspace]
resolver = "2"
members = [
    "audio_volume",
    "badge_inventory",
    "boatinfo_downloader",
    "coding_bat_exporter",
    "dad_bot",
    "soon",
    "spotify_stats",
    "study",
    "tgm_metadetector",
    "world_wide_west",
    "youtube_stats",
]
