[workspace]
members = [
    "badge_inventory",
    "boatinfo_downloader",
    "coding_bat_exporter",
    "dad_bot",
    "soon",
    "study",
    "world_wide_west",
    "youtube_stats",
]
resolver = "2"
