[package]
name = "duckchat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
ureq = { version = "2.9.7", features = ["socks-proxy"] }
