[package]
name = "test_score_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
indicatif = "0.17.7"
minreq = { version = "2.11.0", features = ["json-using-serde", "https"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
