name: badge_inventory

on:
  push:
    paths:
      - "soon/**"

env:
  PROJECT: soon

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
        working-directory: ./${{ env.PROJECT }}
