name: unit_convert

on:
  push:
    paths:
      - "unit_convert/**"

env:
  PROJECT: unit_convert

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
        working-directory: ./${{ env.PROJECT }}
